generate:
  - types
  - client
filter:
    operations:
        - pokemon_list
        - pokemon_retrieve
        - type_retrieve
        - pokemon_species_retrieve
        - ability_retrieve
        - type_list
namingStrategy: idiomatic
